create table if not exists public.blog_content (
  id text primary key,
  data jsonb not null default '{"adBanners":[],"categories":[],"heroVideo":null,"posts":[],"savedAt":null}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.blog_content (id, data)
values ('main', '{"adBanners":[],"categories":[],"heroVideo":null,"posts":[],"savedAt":null}'::jsonb)
on conflict (id) do nothing;

create table if not exists public.celeb_votes (
  id bigint generated by default as identity primary key,
  category text not null check (char_length(category) between 1 and 80),
  voter_hash text not null,
  vote_day date not null,
  created_at timestamptz not null default now(),
  unique (voter_hash, vote_day)
);

create index if not exists celeb_votes_category_idx on public.celeb_votes (category);

create or replace function public.get_celeb_vote_ranking()
returns table(category text, votes bigint)
language sql
stable
security definer
set search_path = public
as $$
  select celeb_votes.category, count(*)::bigint as votes
  from public.celeb_votes
  group by celeb_votes.category
  order by votes desc, celeb_votes.category asc;
$$;

revoke all on public.celeb_votes from anon, authenticated;
revoke all on function public.get_celeb_vote_ranking() from public, anon, authenticated;
grant select, insert on public.celeb_votes to service_role;
grant usage, select on sequence public.celeb_votes_id_seq to service_role;
grant execute on function public.get_celeb_vote_ranking() to service_role;
